openapi: 3.0.3
info:
  title: "Transactions Service API"
  description: "API documentation for [transactions-service](https://github.com/ashwingopalsamy/transactions-service) by [@ashwingopalsamy](https://github.com/ashwingopalsamy)."
  version: "0.0.1"

servers:
  - url: "http://localhost:8080/v1"
    description: "Local Development Server"

tags:
  - name: "Accounts"
    description: "Manage accounts endpoints"
  - name: "Transactions"
    description: "Handle transactions endpoints"

paths:
  /accounts:
    post:
      tags:
        - "Accounts"
      summary: "Create an account"
      description: "Registers a new account with the provided document number."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAccount"
      responses:
        "201":
          description: "Account creation successful"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateAccountSuccess"
        "400":
          description: "Invalid Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "409":
          description: "Conflict"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConflictError"


  /accounts/{id}:
    get:
      tags:
        - "Accounts"
      summary: "Retrieve account information"
      description: "Fetches account information using the provided account ID."
      parameters:
        - name: "id"
          in: "path"
          description: "Unique identifier of the account."
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "Account retrieval successful"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetAccountSuccess"
        "400":
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "404":
          description: "Account Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataNotFoundError"
        "500":
          description: "Internal server error."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnexpectedError"

  /transactions:
    post:
      tags:
        - "Transactions"
      summary: "Create a transaction"
      description: "Records a new transaction associated with an account."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTransaction"
      responses:
        "201":
          description: "Transaction created successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionSuccess"
        "400":
          description: "Bad request."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "500":
          description: "Internal server error."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnexpectedError"

components:
  schemas:
    CreateAccount:
      type: "object"
      required:
        - document_number
      properties:
        document_number:
          type: "string"
          example: "1234567890"

    CreateTransaction:
      type: "object"
      required:
        - account_id
        - operation_type_id
        - amount
      properties:
        account_id:
          type: "integer"
          example: 1
        operation_type_id:
          type: "integer"
          example: 1
        amount:
          type: "number"
          format: "float"
          example: 100.12

    CreateAccountSuccess:
      type: "object"
      properties:
        id:
          type: "integer"
          example: 1
        document_number:
          type: "string"
          example: "1234567890"

    GetAccountSuccess:
      type: "object"
      properties:
        account_id:
          type: "integer"
          example: 1
        document_number:
          type: "string"
          example: "1234567890"

    TransactionSuccess:
      type: "object"
      properties:
        id:
          type: "integer"
          example: 1
        event_date:
          type: "string"
          format: "date-time"
          example: "2025-02-07T15:01:29.082596Z"

    BadRequestError:
      type: "object"
      properties:
        errors:
          type: "object"
          properties:
            id:
              type: "string"
              example: "01947d29-be0a-7dee-9152-dcd2fa85dca4"
            code:
              type: "string"
              example: "invalid_request"
            title:
              type: "string"
              example: "Invalid Request"
            detail:
              type: "string"
              example: "invalid request body"
            status:
              type: "integer"
              example: 400

    DataNotFoundError:
      type: "object"
      properties:
        errors:
          type: "object"
          properties:
            id:
              type: "string"
              example: "01947d29-be0a-7dee-9152-dcd2fa85dca4"
            code:
              type: "string"
              example: "invalid_request"
            title:
              type: "string"
              example: "Account Not Found"
            detail:
              type: "string"
              example: "account not found"
            status:
              type: "integer"
              example: 404

    ConflictError:
      type: "object"
      properties:
        errors:
          type: "object"
          properties:
            id:
              type: "string"
              example: "01947d29-be0a-7dee-9152-dcd2fa85dca4"
            code:
              type: "string"
              example: "conflict"
            title:
              type: "string"
              example: "Conflict"
            detail:
              type: "string"
              example: "failed to perform action. conflict exists"
            status:
              type: "integer"
              example: 409

    UnexpectedError:
      type: "object"
      properties:
        errors:
          type: "object"
          properties:
            id:
              type: "string"
              example: "01947d29-be0a-7dee-9152-dcd2fa85dca4"
            code:
              type: "string"
              example: "unexpected_error"
            title:
              type: "string"
              example: "Internal Server Error"
            detail:
              type: "string"
              example: "An unexpected error occurred."
            status:
              type: "integer"
              example: 500
